on:
  push:
    branches: main

name: Publish

jobs:
  quarto-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git
        run: |
          git config --global user.email "quarto@github.com"
          git config --global user.name "GitHub Action"
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev libgmp3-dev pandoc
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install renv
        uses: r-lib/actions/setup-renv@v2
        
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render and Publish
        run: |
          quarto render entrega4.qmd --output-dir=docs
          quarto publish gh-pages --no-prompt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
