on:
  push:
    branches: main

name: Publish

jobs:
  quarto-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglpk-dev libgmp3-dev pandoc
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install renv
        uses: r-lib/actions/setup-renv@v2
        
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
